### ISSUE TITLE
Edit Links page defaults to custom

### ISSUE THREAD

**Issue by bonelifer** [JulianPrieber/littlelink-custom#113]
On Links page, when you edit a link, it automatically selects "custom" instead of staying on the original selected option.

**Comment by JulianPrieber** [comment]
Thanks for pointing this out.
This is a known issue, and I'm not really sure how to solve it.

Help on this is always welcome.

I might be able to solve this some day.

**Comment by JulianPrieber** [comment]
This has now been fixed with: https://github.com/JulianPrieber/littlelink-custom/commit/38c471ec61393ec562fba6a9e60f0d8858cedaac.

I had to use some trickery, but it works now.

**Comment by JulianPrieber** [comment]
@bonelifer You can already test this new addition, with the latest beta release.

You can learn more about installing beta versions [here](https://littlelink-custom.com/beta-tester#step-2).
