### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [JulianPrieber/littlelink-custom#117]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@whoisshuvam) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by JulianPrieber** [comment]
Hi, thank you for reaching out!

I added a Security Policy with instruction on how to contact me (https://github.com/JulianPrieber/littlelink-custom/commit/3275e9ce15d2e6f4ae7dff4962ec861313d3c995). 

[`littlelink.custom@gmail.com`](mailto:littlelink.custom@gmail.com)

[Security Policy](https://github.com/JulianPrieber/littlelink-custom/security/policy)

**Comment by JamieSlome** [comment]
@JulianPrieber - really appreciate your diligence!

We will get an e-mail sent over to your address shortly with more details :)

Just for reference, the report can also be found directly here:
https://huntr.dev/bounties/7d8a8b57-3174-46ad-b5a2-6e2c671ce7a3/
