### ISSUE TITLE
[FEATURE REQUEST] Add code injection to the <head>

### ISSUE THREAD

**Issue by MagicLike** [JulianPrieber/littlelink-custom#120]
It would be nice to be able to inject code into the `<head>` , e.g. through the `advanced-config.php` so that it is available on every page.
For example, alternative analytics like [Umami](https://umami.is) can be supported this way without having to integrate them.

**Comment by JulianPrieber** [comment]
I will probably add a note clarifying this. However, I can not add this note for existing instances, only to new setups.

**Comment by MagicLike** [comment]
Thank you for clarifying this and adding the note! 😃
