### ISSUE TITLE
Use alternatives to Google services in this project

### ISSUE THREAD

**Issue by MagicLike** [JulianPrieber/littlelink-custom#124]
I think it would be way better for privacy, to use alternatives to Google's favicon API and Google Fonts.

DuckDuckGo's favicon API:
Here is a quick demo for the littlelink-custom website:
https://icons.duckduckgo.com/ip3/www.littlelink-custom.com.ico
![](https://icons.duckduckgo.com/ip3/www.littlelink-custom.com.ico)

[Bunny Fonts](https://fonts.bunny.net):
https://fonts.bunny.net/faq
https://fonts.bunny.net/about

**Comment by JulianPrieber** [comment]
Yessss, this is perfect!

I will change this in a sec.

**Comment by MagicLike** [comment]
Wait a minute please, I am editing this issue right now...

**Comment by MagicLike** [comment]
OK, I also added Bunny Fonts. Now my issue is complete 😄

**Comment by MagicLike** [comment]
If it is ok for you, I am already working on replacing Google with the alternatives in the code.
I will then open a PR.

**Comment by JulianPrieber** [comment]
![chrome_6GB7e1Ypzb](https://user-images.githubusercontent.com/60265788/184919438-d379169b-a1cd-4dd6-9bc1-46a5cf1bbdfa.png)

**Comment by MagicLike** [comment]
I am sorry, but I actually don't know what a dynamically generated favicon is (and for what it is used for in LLC...)
I just read their help site for favicons: https://help.duckduckgo.com/duckduckgo-help-pages/privacy/favicons
It says, that favicons update every few weeks.

**Comment by JulianPrieber** [comment]
A dynamically generated favicon is a favicon that is generated by a script or program on the server, rather than being a static image.

This appears to not be compatible with the DuckDuckGo API, so some websites might not work as they previously did.

I think this is probably still a sacrifice worth doing to get away from the Google ecosystem.

**Comment by MagicLike** [comment]
Ok, now I understand.
DDG also offers a contact for problems, so that would be a way to ask if they could add support for dynamically generated favicons: https://help.duckduckgo.com/duckduckgo-help-pages/company/contact-us

**Comment by MagicLike** [comment]
I Created a PR for Google Fonts #125

**Comment by JulianPrieber** [comment]
@MagicLike if you want, you can implement your changes into the default themes:

https://github.com/JulianPrieber2/galaxy
https://github.com/JulianPrieber/mono

Otherwise, I will do this shortly 👍.

**Comment by MagicLike** [comment]
I have already done it in the integrated versions of those themes:
![grafik](https://user-images.githubusercontent.com/82117109/184930988-05b4eac8-f7b7-4544-86e7-a64ab30c01d8.png)
But I will gladly implement it in the external repos as well.

**Comment by MagicLike** [comment]
Changes in the repos have been made and PRs are open!
