### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ugintl** [JulianPrieber/littlelink-custom#142]
Server type: Apache2
PHP version: 7.4

 Can I use mysql?

Why not install it like a normal laravel app?

**Comment by MagicLike** [comment]
LLC is not "installed", like you describe. You just drop the files in your webspace and you are good to go.
See: https://github.com/JulianPrieber/littlelink-custom#Installation

**Comment by ugintl** [comment]
@MagicLike Yes I have read it and installed it, but I wanted to use mysql. Anyways, I have just setup LLC with mysql database and it is working. If you want to know how I did it, let me know.

**Comment by JulianPrieber** [comment]
This comes probably a bit late :sweat_smile: but moving your database to MySQL is documented in the official docs.

https://littlelink-custom.com/docs/d/database-settings/#using-mysql
