### ISSUE TITLE
Allow admin to customize user permissions

### ISSUE THREAD

**Issue by ugintl** [JulianPrieber/littlelink-custom#146]
As an admin, I want to be able to create roles and customize user permissions. Is it something in your to do list?

**Comment by MagicLike** [comment]
It would be better to add such feature requests to #49 instead of opening a new issue each time.

@JulianPrieber How about mentioning #49 in the README so that each new feature request could be added directly there?

**Comment by ugintl** [comment]
@MagicLike Please check #49

**Comment by MagicLike** [comment]
@ugintl LGTM

**Comment by ugintl** [comment]
@MagicLike What is mean by LGTM?

**Comment by MagicLike** [comment]
@ugintl Looks Good To Me

**Comment by JulianPrieber** [comment]
> @JulianPrieber How about mentioning #49 in the README so that each new feature request could be added directly there?

I thought that was kind of a given, but yeah that's probably a good idea.
