### ISSUE TITLE
Wrong home page

### ISSUE THREAD

**Issue by alfonsomujica** [JulianPrieber/littlelink-custom#169]
Currently my website goes to a "root file system page" (visit page: hoogloo.me) and NOT an actual home page.
I want it to be like this "hoogloo.me" and NOT "hoogloo.me/little-custom/"

**Comment by JulianPrieber** [comment]
Then just move everything from your "little-custom" folder to the root directory.
Installing LittleLink Custom is pretty much like installing WordPress.
