### ISSUE TITLE
[UX] Add link shows more information unrelated to the form

### ISSUE THREAD

**Issue by Ryuno-Ki** [JulianPrieber/littlelink-custom#173]
On the demo instance when I add a link I can find an accordion below the form to explain the functionality.

However, the elements described there seem to have little to do with the form fields.
Is this element meant to be shown elsewhere?

**Comment by JulianPrieber** [comment]
This?

![chrome_X10q4VzLWU](https://user-images.githubusercontent.com/60265788/193611711-24134a55-a389-48b3-9750-a3c84c2febf0.png)

**Comment by JulianPrieber** [comment]
This is the explanation for certain button types. These explain critical functions for buttons that are unique from other buttons.
I couldn't tell you a better place for it.

Granted, this was a pretty hasty solution and is not intended to be permanent. We have our eyes on a pretty good solution for this.

Are you using Discord by any chance?

**Comment by Ryuno-Ki** [comment]
> This is the explanation for certain button types. These explain critical functions for buttons that are unique from other buttons. I couldn't tell you a better place for it.

It's out of context in this specific case, I think.

> Granted, this was a pretty hasty solution and is not intended to be permanent. We have our eyes on a pretty good solution for this.

Okay, so it's already known. Fine for me.

> Are you using Discord by any chance?

DMed you in Mastodon.

**Comment by JulianPrieber** [comment]
> DMed you in Mastodon.

Our social account is managed by me and another team member. I will DM you the details from my personal account to avoid confusion for the future.
