### ISSUE TITLE
Feature Request: let pages be replaced by links

### ISSUE THREAD

**Issue by jaschaurbach** [JulianPrieber/littlelink-custom#193]
It would be great when acessing /panels/pages to not only edit the content of the different pages but give the possibility to enter a URL to link to an external page instead of editing content. 

My use case would be to link to an already existing contact page instead of entering the content again and keep two different pages up to date.

**Comment by JulianPrieber** [comment]
Like I stated in https://github.com/JulianPrieber/littlelink-custom/issues/195 we are working on an update that add further customization options to those links, like: the ability to rename entries and link to any page.

With an option in the Advanced Config, you actually can rename the Home footer link and point the link to any external page you like.

So you could just disable the contact link (like described in https://github.com/JulianPrieber/littlelink-custom/issues/195) rename the Home link and point it to your contact page.

Hope this helps 👍

**Comment by JulianPrieber** [comment]
Simply comment here if you need any further assistance configuring this 👍
