### ISSUE TITLE
Feature Request: Remove page from footer list

### ISSUE THREAD

**Issue by jaschaurbach** [JulianPrieber/littlelink-custom#195]
Have the possibility to remove creation entries form the footer. 

My use case would be to remove the Home Button and Terms button from the list

**Comment by jaschaurbach** [comment]
Sorry, I just did not finis the title: Feature Request: Remove page from footer list

**Comment by JulianPrieber** [comment]
Good news, this is already possible with an option in the Advanced Config!
In the "Footer links" section, you can disable individual entries on your footer list.

We are working on an update that add further customization options to those links, like: the ability to rename entries and link to any page.

**Comment by JulianPrieber** [comment]
Simply comment here if you need any further assistance configuring this 👍

**Comment by jaschaurbach** [comment]
Oh my! Thanks, I was not aware of it. thank you!
