### ISSUE TITLE
Feature Request: have fontawesome locally in the installation

### ISSUE THREAD

**Issue by jaschaurbach** [JulianPrieber/littlelink-custom#201]
Hi,

it would be awesome (pun intended) if Font Awesome would be on server side that no more call are made to their servers. In my case it would be to avoid GDPR incompliance.

Thanks for considering.

**Comment by jaschaurbach** [comment]
Just an idea: Maybe it would be great to use https://forkaweso.me/ -the syntax is the same as FA but add icons e.g. for Liberapay.

**Comment by JulianPrieber** [comment]
> it would be awesome (pun intended) if Font Awesome would be on server side that no more call are made to their servers. In my case it would be to avoid GDPR incompliance.

We included Font Awesome locally for now https://github.com/JulianPrieber/littlelink-custom/commit/56e17b9fd50cbc03ed2858bd2cca805a856be538

**Comment by JulianPrieber** [comment]
> Just an idea: Maybe it would be great to use https://forkaweso.me/ -the syntax is the same as FA but add icons e.g. for Liberapay.

I added this to the to-do list https://github.com/JulianPrieber/littlelink-custom/discussions/49

**Comment by My1** [comment]
maybe also have the bunny.net fonts locally too?

**Comment by JulianPrieber** [comment]
@My1 
> maybe also have the bunny.net fonts locally too?
if that's okay I can open a new issue but thought I'd ask first

I already opened a thread under this discussion for this https://github.com/JulianPrieber/littlelink-custom/discussions/222.

Feel free to put your thoughts there. 👍
