### ISSUE TITLE
Root Directory on Subdomain

### ISSUE THREAD

**Issue by jandreaucodes** [JulianPrieber/littlelink-custom#213]
Just working on getting this installed and I've setup a custom subdomain on my main domain for the app to run.

It throws an error (Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2".) if I upload the contents of the littlelink-custom directory to the root folder of that subdomain.

However, if I upload the contents in a folder (of any name), the app works as desired. Can I not run it in a root directory of a subdomain?

I'd like links.mydomain.com and not links.mydomain.com/links (or some other subdirectory)

**Comment by JulianPrieber** [comment]
Depending on what solution you used to set up your subdomain, you'll need to select PHP 8 as your PHP version.

If you cannot do this, you'll have to run the command `composer update` in the LittleLink directory.

**Comment by jandreaucodes** [comment]
PHP 8.0.14 is active on the subdomain, which is why the code works in the subdirectory, I think.

**Comment by jandreaucodes** [comment]
I see the issue. Updating PHP from 7 to 8 on the subdomain didn't take effect right away. Once I restarted nginx, everything is working as expected. Thanks for the help!
