### ISSUE TITLE
Visitor Analytics

### ISSUE THREAD

**Issue by root9191** [JulianPrieber/littlelink-custom#215]
Hello,
i just installed the newest Release 3.0.1, but since yesterday the Visitor Analytics are at 0:
![image](https://user-images.githubusercontent.com/47309435/202235795-16e88dec-374d-40f6-a4b6-1472d9f4965f.png)

Is there something wrong in my LLC Instance?

**Comment by JulianPrieber** [comment]
The visitor analytics are bound to your littlelink name (@admin). If you change that, this will reset your analytics.

**Comment by root9191** [comment]
My Littlelink Name is Custom - Can i change it from @admin to my name?

**Comment by JulianPrieber** [comment]
You can change it as much as you want, just keep ind mind that this will reset your analytics data.

**Comment by root9191** [comment]
Where do i do this? In the .env File or advanced-config?

**Comment by JulianPrieber** [comment]
Right here ![chrome_h28pGU1520](https://user-images.githubusercontent.com/60265788/202237751-4f57e632-8ef0-4d2e-86a1-39e7d33ddd7b.png)

**Comment by JulianPrieber** [comment]
Right. And it will always reset to 0 when you change that name.

Did you change that name in the last couple of days?

**Comment by root9191** [comment]
Nope, just when i installed it first and then never again.
I have also set the Home Url to my Custom Name so the Address looks cleaner. Could this be related to?

**Comment by root9191** [comment]
And i have emojis in my Display Name, if this could be related to!?

**Comment by root9191** [comment]
Ok is there something i can check on my Side? Maybe there are some write access problems on my Hosting.

**Comment by JulianPrieber** [comment]
I mean, it's definitely none of that. 
It would be interesting if you could reproduce the error and find what's causing it.

**Comment by root9191** [comment]
Ok if there is a logfile or something else i could check?

**Comment by JulianPrieber** [comment]
There is, but I doubt you will find something useful in there

**Comment by root9191** [comment]
OK kinda interesting why this is not working. And you can not reproduce it?

**Comment by JulianPrieber** [comment]
I haven't really tried reproducing it yet, I'm still working on the next version.

**Comment by JulianPrieber** [comment]
Maybe the update broke the visitor count?

It might be interesting to see if the visitors get tracked in the database.

**Comment by root9191** [comment]
Could not be because i started from scratch with the newest Version..

**Comment by root9191** [comment]
Ok this Visitor Analytics is since Version 3 or earlier?

**Comment by JulianPrieber** [comment]
Yeah, since version 3, but it had multiple iterations in the beta stage.

**Comment by escuco** [comment]
Same issue here, the visitor analytics (today, week, ...) remaining at "0". The counter "total links" and "top links" are counting fine.

But for me it's not problem, since I'm using Matomo.

**Comment by root9191** [comment]
How did you implement Matomo? Did you pasted the Code somewhere?

**Comment by escuco** [comment]
You can paste the code into the "Analytics" area in the advanced config.

**Comment by root9191** [comment]
Cool, Thank you!

**Comment by root9191** [comment]
> You can paste the code into the "Analytics" area in the advanced config.

Hi, does the outgoing refer work for you in matomo?

**Comment by escuco** [comment]
Only for the links in the footer pages, not for the linked buttons.

**Comment by root9191** [comment]
OK, i disabled everything here so i see nothing :)
