### ISSUE TITLE
Sorting of Links not possible between pages

### ISSUE THREAD

**Issue by nicls** [JulianPrieber/littlelink-custom#226]
Hello,

When you have more than ten elements on the "Your Links" page, it is not possible to move elements from the second page to the firs page and vice versa. To enable sorting all elements need to be on a single page.

Could  you please have a look?

Its a great application! Thank you for offering it to the public!
Best
Nkls

**Comment by JulianPrieber** [comment]
Hey Nkls,

Sorry, that option got lost in with the front-end update. 
You can see all links by visiting `example.com/studio/links/all`.

Regards

**Comment by nicls** [comment]
Oh great, thank you for your fast reply!

**Comment by JulianPrieber** [comment]
https://github.com/JulianPrieber/littlelink-custom/commit/d76473177e682e39ad0f6c9d39ce5f9132518e7a
