### ISSUE TITLE
Same questions and problems

### ISSUE THREAD

**Issue by lastsamurai26** [JulianPrieber/littlelink-custom#23]
Is there a way to show the login and register button on every page ?

as I have changed the main page so that I can beautify the home page and not have the Little link default page. 

Is there also a way to go directly to the studio after logging in without having to type /studio/index ? 

I also noticed that I can't change my own password as a user. 

is there a way to get an error message if you enter a wrong URL with domain.com/ as an example?

**Comment by JulianPrieber** [comment]
The easy answer is no.

If you used the built-in option to set profile as homepage in the config, you can find the login/register page at `yourdomain.com/home` or perhaps `yourdomain.com/if-in-a-sub-folder/home`. Otherwise, there is no built-in functionality for what you're looking for.

Now, if you know a bit about HTML/PHP, you could add the register/login button to every page fairly easily.

Your problem with having to type '/studio/index' can be solved by editing the routes in `/routes/web.php`, but this might break some automatic redirections, so you would have to edit those as well.

Also, thank you for pointing the password thing out, I will look into it.

Now for your last mention, I think [this](https://www.positronx.io/how-to-create-custom-404-page-in-laravel-application/) might be what you're looking for. Alternatively, this has to be done via your web hosting software.

**Comment by lastsamurai26** [comment]
I think :-( I expressed myself strangely.


1. littlelink is running fulldomain but in .env I have set HOME_URL to main, which means that the domain.de no longer shows the default page that littlelink brings but one of a registered user.
This means that either I use HOME_URL = "" or I have to enter /studio/index when I want to go to the studio. 

2. if I want to add a link via Add Link the URL must not end with a /, however it saves this link but if you call it you get an error page. Can this be intercepted directly when saving? 
It makes no sense to me why a URL may not end with a / but an error message when saving would be great :-)

3. register and Login -> can you tell me where I can do that? Then I could indeed do this 

4. password topic  ->  thanks :)

**Comment by JulianPrieber** [comment]
Ah, I see.

1. LittleLink Custom is set up in a way that you don't really need to use the HOME_URL, you can just leave that empty. 

2. I'm still working on a filter system for that exact case. I think I know how to reject a "/" at the end of a URL, but I still haven't gotten to how to display a feedback prompt notifying the user of the problem with the URL.

3. Now, register and login implementation can be done very easily by adding simply copying the code from `/resources/viewshome.blade.php` and adding the login section at the top of the body tag in the wanted pages.

The section:
```
<div class="sign" style="margin-top: 30px; text-align: right;">
        @if (Route::has('login'))
                @auth
                    <a href="{{ route('studioIndex') }}" class="underline spacing">Studio</a>
                @else
                    <a href="{{ route('login') }}" class="underline spacing">Log in</a>
                    @if (Route::has('register') and $page->register == 'true')
                        <a href="{{ route('register') }}" class="underline spacing">Register</a>
                    @endif
                @endauth
          @endif
</div>
```

**Comment by JulianPrieber** [comment]
Perhaps something like this:
```
<div class="sign" style="margin-top: 30px; text-align: right;">
    <a href="{{ route('login') }}" class="underline spacing">Log in</a>
    <a href="{{ route('register') }}" class="underline spacing">Register</a>
</div>
```

**Comment by lastsamurai26** [comment]
> Perhaps something like this:
> 
> ```
> <div class="sign" style="margin-top: 30px; text-align: right;">
>     <a href="{{ route('login') }}" class="underline spacing">Log in</a>
>     <a href="{{ route('register') }}" class="underline spacing">Register</a>
> </div>
> ```

thanks i  will check this :)

**Comment by lastsamurai26** [comment]
thanks :) 

I will leave out the database .sqlite and .env as these are already present - I can overwrite all the others. 
I will test this tomorrow and keep you informed. An update of the database itself is not necessary?

**Comment by JulianPrieber** [comment]
> An update of the database itself is not necessary?

The database has not been changed and is not needed for the update.

**Comment by JulianPrieber** [comment]
> 2. if I want to add a link via Add Link the URL must not end with a /, however it saves this link but if you call it you get an error page. Can this be intercepted directly when saving?

The last two commits [#303](https://github.com/JulianPrieber/littlelink-custom/commit/268c6557a1174d24e1014e00d0c03d28fe6bae59) and [#304](https://github.com/JulianPrieber/littlelink-custom/commit/5e5ce391b971625f7be3dea997b5db158902c7ed) added checks if edited and newly added links begin with "https://" and not end with a "/".

If you now add a link as "google.com/" it would get saved as "https://google.com" for example.

I'm planning on publishing the new release later today, so if all goes well, you can try out the full thing tomorrow.

**Comment by lastsamurai26** [comment]
> 
> If you now add a link as "google.com/" it would get saved as "https://google.com" for example.
>

Does this mean that if I save without https:// and without ending / it saves it as https://domain.de but what happens if I save it as https://domain.de/ ? Then the rewrite doesn't works. Can I filter this somehow via htaccess or directly on save ? 

I have to say :) your work is really great!!! I like littlelink custom better than all the others from littlelink

**Comment by lastsamurai26** [comment]
Thank you :-) it works. 

Password change as well as the one with the links 


**Closed :-)**
