### ISSUE TITLE
allow embed html code for odysee & youtube videos

### ISSUE THREAD

**Issue by nobaraos12** [JulianPrieber/littlelink-custom#230]
title

**Comment by JulianPrieber** [comment]
This feature is planned to come out if some future release.

Added to the list: https://github.com/JulianPrieber/littlelink-custom/discussions/49

**Comment by nobaraos12** [comment]
also would like to add if you made a section in the websites metacode you can add mastodon html verification, so a user wouldn't have to make another link element they could just paste into the websites meta code
