### ISSUE TITLE
Instagram doesn't trust cert 

### ISSUE THREAD

**Issue by nobaraos12** [JulianPrieber/littlelink-custom#234]
when adding an little link demo url to an users profile on instagram, then clicking the link. Instagram displays this message 

![signal-2022-11-26-090802](https://user-images.githubusercontent.com/118019611/204100701-ab170cd3-cf2e-47ff-85e9-6ab678b03c81.png)

**Comment by JulianPrieber** [comment]
From what I've gathered, this appears to be an issue with the client (i.e. you).
Most people seem to land on some discrepancy with your local validation of the certificate.
Mostly this can happen when your system time is not 100% accurate.

There are a lot of guides online that supposedly fix this issue, but I can't give you any confirmation if they would help.

**Comment by JulianPrieber** [comment]
I will still look into this and see if I maybe find anything definitive.

**Comment by nobaraos12** [comment]
it seems to be a non constant behavior might be an instagram issue with links, as sometimes they release certain beta builds to a handful of users randomly. It might be that situation
