### ISSUE TITLE
Issues with linked instagram pages 

### ISSUE THREAD

**Issue by nobaraos12** [JulianPrieber/littlelink-custom#235]
I've noticed when you link an instagram page in little link custom demo it goes to "problem loading page"

Reproduce
1. add an instagram profile link to little link
2. open your little link
3. tap your instagram link on your little link
4. it will not load the page despite being an proper url

extra findings:

I've noticed it works on an iphone x running ios 16 
I've also noticed it doesn't work on firefox (107.0 (64-bit)) Flatpak

**Comment by JulianPrieber** [comment]
I'm a bit confused. Is this related to https://github.com/JulianPrieber/littlelink-custom/issues/234?

Like which page doesn't load, your LittleLink page or Instagram?

Does this only happen with Instagram?

**Comment by JulianPrieber** [comment]
I did some testing and I can't load Instagram profiles with my Firefox install either. This happens regardless of if accessed from the LittleLink Custom instance or not.
This appears to be unrelated.

**Comment by nobaraos12** [comment]
understandable
