### ISSUE TITLE
can't drag elements from page 2 to page 1

### ISSUE THREAD

**Issue by nobaraos12** [JulianPrieber/littlelink-custom#247]
using the demo site, I can't drag an header from page 2 to page 1 to organize it

**Comment by JulianPrieber** [comment]
![chrome_wo7sJiFixm](https://user-images.githubusercontent.com/60265788/205435034-29b9281f-caed-4f6f-be06-bea687118e3a.png)
![chrome_7ipPiVCwYx](https://user-images.githubusercontent.com/60265788/205435036-d2d22586-975a-44d8-8cf2-2d7241a3c018.png)

You can just use this option to show all links at once.
