### ISSUE TITLE
BadMethodCallException "https://littlelink-custom.llc.ovh/studio/links"

### ISSUE THREAD

**Issue by nobaraos12** [JulianPrieber/littlelink-custom#255]
Using the demo of littlelink custom when navigating to https://littlelink-custom.llc.ovh/studio/links on firefox running fedora it displays a new window.
![Screenshot from 2022-12-06 10-02-06](https://user-images.githubusercontent.com/118019611/205947400-8a9c8bbe-9391-468c-ac9c-14cc5bdcf5be.png)

**Comment by JulianPrieber** [comment]
Just clear your cookies.

**Comment by JulianPrieber** [comment]
Might be solved now I'm not sure..

**Comment by nobaraos12** [comment]
> Just clear your cookies.

this worked
