### ISSUE TITLE
BUG: Clear icon cache forces redirect to main page 

### ISSUE THREAD

**Issue by nobaraos12** [JulianPrieber/littlelink-custom#256]
Using the demo on firefox (fedora 36)

**Comment by JulianPrieber** [comment]
Should be fixed now

**Comment by JulianPrieber** [comment]
Would you like to join our [beta tester team](https://littlelink-custom.com/beta-tester)?

**Comment by nobaraos12** [comment]
> Would you like to join our [beta tester team](https://littlelink-custom.com/beta-tester)?

would love to but not a member of discord nor plan to be

**Comment by JulianPrieber** [comment]
[Matrix](https://us.littlelink-custom.com/going/11) might be a good compromise. We have a bridged server, but not everything is fully setup yet.

**Comment by nobaraos12** [comment]
> [Matrix](https://us.littlelink-custom.com/going/11) might be a good compromise. We have a bridged server, but not everything is fully setup yet.

thank you, went ahead and emailed you

**Comment by nobaraos12** [comment]
> > [Matrix](https://us.littlelink-custom.com/going/11) might be a good compromise. We have a bridged server, but not everything is fully setup yet.
> 
> thank you, went ahead and emailed you also

okay thank you, though I have yet to receive it

**Comment by JulianPrieber** [comment]
https://matrix.to/#/#LittleLinkCustom:matrix.org

this?
