### ISSUE TITLE
Reorder links isn't working

### ISSUE THREAD

**Issue by jam3sperkins** [JulianPrieber/littlelink-custom#279]
Hey there,

Still loving this product.

Recently updated to v3.2.2 and found that I can no longer re-order links. It looks like the option to manually order based on the number has gone as well. So when I drag a link, I just get a popup with an image that doesn't load.

In the console I see I am getting 2 x 404 errors when dragging a link:
jquery.min.js:2          POST https://domain-here/links/studio/studio/sort-link 404
loading.gif:1          GET https://domain-here/links/studio/img/loading.gif 404

Thanks,
James

**Comment by lastsamurai26** [comment]
Hello, 

on what basis do you use LLC ? 

I just tested this on the 3.2.2 version under Apache and Nginx and unfortunately could not reproduce this error 

to reorder via number isn't availble anymore you change the order via the red marked function 
![image](https://user-images.githubusercontent.com/3257844/208832362-072507e5-b249-44bc-9d5d-cdf35e779acc.png)

**Comment by JulianPrieber** [comment]
@jam3sperkins are you using the web version or Docker?

**Comment by jam3sperkins** [comment]
@JulianPrieber  I am using the web version on apache. I guess this maybe from upgrading a couple of times.

However interestingly, I've just tried again after trying a few times a few days apart before reporting and it now works. Maybe there was a cache issue in my browser.

I guess we can close it.
