### ISSUE TITLE
Diagnostic checkmarks hard to see in dark mode

### ISSUE THREAD

**Issue by BWPanda** [JulianPrieber/littlelink-custom#280]
On the Diagnostics page (`/panel/config#5`) the checkmarks in the right-hand column are hard/impossible to see when in dark mode:

![image](https://user-images.githubusercontent.com/2385329/208882632-2822dac6-9782-4f10-9444-b7380b5a9563.png)

![image](https://user-images.githubusercontent.com/2385329/208882733-93210bb5-4526-45f3-83e5-d463083eb0ff.png)

**Comment by JulianPrieber** [comment]
Ah, I see. I didn't think this would ever be a problem. Apparently your system/browser uses different styling for emojis, coincidentally making them the same color as our background.

For they look like this:
![screencapture-localhost-littlelink-custom-panel-config-2022-12-21-13_29_14](https://user-images.githubusercontent.com/60265788/208905732-7cb287c1-372a-432f-af10-97f069345afc.png)

I'll change them to proper icons to get consistent results.
