### ISSUE TITLE
Unique index users_name_unique

### ISSUE THREAD

**Issue by valimero** [JulianPrieber/littlelink-custom#288]
Hello !

Is there a reason to have the unique index "users_name_unique" ?

2 users cannot have the same name..

**Comment by JulianPrieber** [comment]
I'm not sure if I understand your question.

You cannot have two users with the same name.
And we have to prevent this from happening.

**Comment by valimero** [comment]
I need to create two users with the same name.

Today, if I try to do it, I have this error:

```
Illuminate\Database\QueryException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'John Doe' for key 'users_name_unique' (SQL: update `users` set `name` = John Doe, `email` = w4aCkTwB@example.com, `littlelink_name` = ?, `littlelink_description` = ?, `role` = user, `users`.`updated_at` = 2022-12-29 18:34:24 where `id` = 33)
```

So I'm asking if there is a specific reason to forbid same names in mysql..

**Comment by JulianPrieber** [comment]
This would definitely break stuff if this would be possible.

**Comment by valimero** [comment]
@JulianPrieber Do you have an example ?

**Comment by JulianPrieber** [comment]
I haven't fully looked into this. You can remove the unique requirement and use your instance as normal for the most part.
For future updates, I'd like to keep the unique requirement.

I'm not entirely sure if our social login solution works properly and security without it.
Again, Í never really had an intensive to test this out, as I'd rather not change anything that is working fine.

I might actually consider looking into this to see if this is viable to have as a full feature.

**Comment by JulianPrieber** [comment]
We are now testing this in the latest beta.
