### ISSUE TITLE
Forgot password page doesn't work

### ISSUE THREAD

**Issue by Permanently** [JulianPrieber/littlelink-custom#289]
Simple as that - the forgotten password page doesn't work. On my test instance, it appears with a 404, with no error code.

I tried this on the demo, and it came back a lot worse [with this](https://criminal.host/umzot8y61w6n.png).

**Edit:** Not sure if it's worth mentioning, but I will do since the readme doc says it should be possible - the register page also doesn't work. This is visible both on my test instance and the live demo, [and they produce the same results](https://criminal.host/xgjjtikp8ve4.mp4).

**Comment by lastsamurai26** [comment]
The register page is still directly accessible but does not display anything, this is intentional.
But a registration is disabled 

@JulianPrieber can you take a look on this ?

**Comment by Permanently** [comment]
Registration is supposed to be enabled for the instance I'm testing, yet [the registration page nor a button for it still doesn't show](https://criminal.host/xy85ba7src5y.png).

**Comment by JulianPrieber** [comment]
This is fixed in the latest beta version: https://criminal.host/umzot8y61w6n.png

The other thing I'm not sure about.

**Comment by Permanently** [comment]
Alrighty. Whilst testing, I've found that the email verification page [also returns a 404](https://criminal.host/idczqkqk4co3.png).

**Comment by JulianPrieber** [comment]
This should work since the latest update.
I'm marking this as done. Feel free to comment under here if you encounter any problems regarding this.
