### ISSUE TITLE
Unable to upload/apply themes

### ISSUE THREAD

**Issue by enthuzy** [JulianPrieber/littlelink-custom#293]
Platform: `AlmaLinux v8.7.0`
Server type: `Apache2 ...`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

New installation with the latest version read the very short requirements and everything installs fine. When I try to upload any theme, I get an error: "Call to undefined function App\Http\Controllers\system()" app/Http/Controllers/UserController.php:588

After exiting the error page and returning to the admin, the theme is populated in the dropdown twice. If applied, the preview displays a page with no .css applied.

I have installed this before on another server with no issues but older version.

**Comment by JulianPrieber** [comment]
With our current solution for handling theme uploads and updates, this is not fixable.

For the most part, this error only appears on shared hosting solutions, but can happen on other systems.

You could upload themes manually. For that, you'd have to place the unzipped folder into your themes folder in your installation. Just keep in mind that the theme updater won't function properly, either.

I'd recommend you use the docker version if you can. This ensures everything is working as intended.


**I will look into this once again and try to find a solution that works for everyone.**

**Comment by enthuzy** [comment]
Thank you for the reply. Interestingly enough, the instance where it is working is on a shared host while this broken instance is on a VPS and the updater works on this instance as well. Perhaps there's some setting I can tweak to get it working, but I will try manually installing themes or a docker container.

Cheers!
