### ISSUE TITLE
/verify-email URL doesn't exist

### ISSUE THREAD

**Issue by Permanently** [JulianPrieber/littlelink-custom#300]
Platform: `Ubuntu 22.04 LTS`
Server type: `Apache2`
PHP version: `8.1.14`

When a user hasn't verified their email, they may try to login and use the studio. I imagine an email verification reminder is supposed to show, but it doesn't. [See demonstration here](https://criminal.host/zwd1uqs73s9w.gif). 

Worth noting that /verify-email doesn't work, but /verify-email/{id}/{hash} does.

**Comment by lastsamurai26** [comment]
which version of LLC you are using ?
After register a new Account in my testing Instance and login after clear cookies and cache a get this messege when i try to login 

![image](https://user-images.githubusercontent.com/3257844/214769853-ea4a1d85-dffa-45b7-ad4f-8ec6a75f83c3.png)

**Comment by Permanently** [comment]
This is the latest version of LLC that I was using.

Will update with comments once I get past the barrier of #308.

**Comment by Permanently** [comment]
[As quoted](https://github.com/JulianPrieber/littlelink-custom/issues/308#issuecomment-1407748114) from #308: 

> This also fixed #300 somehow. I'm genuinely in awe as to how.
