### ISSUE TITLE
Themes doesn't working

### ISSUE THREAD

**Issue by DerKartdomi** [JulianPrieber/littlelink-custom#310]
Platform: `Plesk Webhost`
Server type: `NGINX/Apache2 Plesk Webhost`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)
Hello, I have the problem that my themes doesn't working. If I enable it the css etc doesn't working and the website is buggy. Can someone help me with this problem?

**Comment by lastsamurai26** [comment]
can you provide us more informations 


your theme is based on which theme ?

**Comment by DerKartdomi** [comment]
it is on all except Galaxy

**Comment by JulianPrieber** [comment]
Can you upload new themes?

**Comment by DerKartdomi** [comment]
Yes, I've tried several times but it's always the same

**Comment by DerKartdomi** [comment]
![Screenshot_2023-01-31-15-52-09-128_com android chrome](https://user-images.githubusercontent.com/67392090/215793940-cccaf4e2-edce-49a4-ba61-cf798d0c3e0e.jpg)

**Comment by JulianPrieber** [comment]
Alright, I'd need your browser console log to investigate further. For this, you'd need to access your page directly with a desktop browser and open the console tab. Then please screenshot any errors that might pop up.

**Comment by DerKartdomi** [comment]
https://screen.magic-pics.tk/FOku9/KazoHeqI88.png

**Comment by JulianPrieber** [comment]
Um, there is no theme called "starga". Did you change any of the folder names or uploaded a custom theme?

**Comment by DerKartdomi** [comment]
I changed the name and this works. But why is the wrong name in there if I upload the theme?

**Comment by JulianPrieber** [comment]
The name displayed in the panel is the name theme's readme.md

`*	Theme Name: Galaxy`
