### ISSUE TITLE
New Install Not Working

### ISSUE THREAD

**Issue by ZachHandley** [JulianPrieber/littlelink-custom#326]
Platform: `Ubuntu 22.04 LTS`
Server type: `Apache2`
PHP version: `8.2`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

After install on an Nginx server it is just giving me this error in the error.log

`2023/02/18 21:11:56 [error] 515911#515911: *102 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/zachhandley/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/zachhandley/index.php on line 34; PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/zachhandley/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/zachhandley/index.php:34
Stack trace:
#0 {main}
  thrown in /var/www/zachhandley/index.php on line 34" while reading response header from upstream, client: 172.70.55.34, server: zachhandley.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "www.zachhandley.com"`
  
Can't get the install page to show up even after deleting and trying again

I am aware this is Laravel, and I attempted to install it using `composer install` but it only fixed the vendor problem not the actual issue which is the install page never shows to setup the DB or anything

**Comment by JulianPrieber** [comment]
Hey,

When trying to set up a new instance, we recommend using the latest release, not the source files. This doe already come with all necessary dependencies to run LittleLink Custom.

If you wish to build your own instance from source, you'll have to install the dependencies and seed the database on your own.

**You can do this with the following commands:**

```
php artisan migrate
php artisan db:seed 
php artisan db:seed --class="AdminSeeder"
php artisan db:seed --class="PageSeeder"
php artisan db:seed --class="ButtonSeeder"
```

Please note that this will disable the installer and you can login with the default credentials:

**email:** `admin@admin.com`
**password:** `12345678`

**Comment by ZachHandley** [comment]
OH. My bad. Thank you!
