### ISSUE TITLE
Text input limited to 255 characters

### ISSUE THREAD

**Issue by cln-io** [JulianPrieber/littlelink-custom#328]
LittleLink Custom v3.3.6, set up on MySQL

I think there is a need to update some database fields either in length or in type, 

In the profile, the input/text is limited to 255
![image](https://user-images.githubusercontent.com/7887972/220403284-b3785c26-3051-4cf2-9b0c-4a753011d2eb.png)

the same for paragraphs as a link, its limited to 255 characters

![image](https://user-images.githubusercontent.com/7887972/220404102-44575ff2-41b1-4002-a3c4-2e9cbc3284c4.png)

- Table: `users > littlelink_description` change from VARCHAR(255) to **TEXT** to allow more text than 255 characters.
- Table: `links > title` change from VARCHAR(255) to **TEXT** to allow more text than 255 characters.

I've looked for the database creation queries within the source, and was hoping to make a PR for it, but was somehow unable to locate where those SQL queries are located 🤦🏻‍♀️

**Comment by JulianPrieber** [comment]
https://github.com/JulianPrieber/littlelink-custom/blob/main/database/migrations/2014_10_12_000000_create_users_table.php

**Comment by JulianPrieber** [comment]
The string method in Laravel's migration builder is not limited to 255 characters by default.

**Comment by JulianPrieber** [comment]
I just tested this and you're right, it seems that MySQL limits these fields for some reason while SQLite doesn't.

**Comment by JulianPrieber** [comment]
Something like this might work, I'm not sure: `$table->string('littlelink_description', 1000)->nullable();`

**Comment by JulianPrieber** [comment]
@cln-io 

I wrote this code to convert an existing database:

```
<?php
// Connect to the database
$servername = env('DB_HOST');
$username = env('DB_USERNAME');
$password = env('DB_PASSWORD');
$dbname = env('DB_DATABASE');

$conn = mysqli_connect($servername, $username, $password, $dbname);

// Modify the column
$sql = "ALTER TABLE users MODIFY littlelink_description VARCHAR(1000)";

if (mysqli_query($conn, $sql)) {
    echo "Column modified successfully";
} else {
    echo "Error modifying column: " . mysqli_error($conn);
}

// Close the connection
mysqli_close($conn);

?>
```

**Comment by JulianPrieber** [comment]
I think using Laravel, this would be something like: 
```
        Schema::table('users', function (Blueprint $table) {
            $table->string('littlelink_description', 1000)->change();
        });
```
