### ISSUE TITLE
Change favicon of littlelink-custom ?

### ISSUE THREAD

**Issue by accnetdev** [JulianPrieber/littlelink-custom#350]
Hi,
I would like to change the littlelink-custom script's favicon, how to do it ?
Regards

**Comment by JulianPrieber** [comment]
![chrome_05iF9sFeSP](https://user-images.githubusercontent.com/60265788/223470755-dcfc2e9b-c505-4412-97e1-b1beee66f89f.png)

On the "Home Page" tab (example.com/panel/site) by simply uplaoding a favicon.

**Comment by accnetdev** [comment]
Many thanks, sorry for the question as it was easily findable...
Congratulations for your script.
Have a good day.
