### ISSUE TITLE
After upgrade to 3.5.0, My Page Logo is not displaying

### ISSUE THREAD

**Issue by fame-odoo** [JulianPrieber/littlelink-custom#356]
Platform: `Ubuntu 22.04 LTS`
Server type: `NGINX/Apache2 ...`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

`<img alt="avatar" class="rounded-avatar fadein" src="https://mylink/img/1.png" srcset="https://mylink/littlelink/images/avatar@2x.png 2x" width="128px" height="128px" style="object-fit: cover;">`

`https://mylink/littlelink/images/avatar@2x.png` this link is not displaying correctly, it is displaying as the default icon

**Comment by JulianPrieber** [comment]
Please update again one more time.

**Comment by JulianPrieber** [comment]
https://github.com/JulianPrieber/littlelink-custom/issues/358
