### ISSUE TITLE
Default Avatar on mobile devices

### ISSUE THREAD

**Issue by stadler0** [JulianPrieber/littlelink-custom#358]
If a user changes his own avatar it shows up on PC but not on mobile devices. There it will show the default avatar. I currently use the docker version.

**Comment by JulianPrieber** [comment]
Please update again one more time.

**Comment by stadler0** [comment]
When I got to example.com/update I get the message "No new version". I also reinstalled everything in a new container and pulled the docker repo but nothing changed about the avatar not showing up.

**Comment by JulianPrieber** [comment]
Can you please enter your page URL into [this tool](https://www.site-shot.com/) and see if the image displays there?

**Comment by stadler0** [comment]
![image](https://user-images.githubusercontent.com/101025394/224440420-ac6e9620-57a1-4bfa-90c1-138d125b8f0e.png)

It still does not display on mobile.

**Comment by JulianPrieber** [comment]
Did you try uploading your avatar again?

**Comment by stadler0** [comment]
Just tried it and it still wont show up. I used a .png file for the avatar, could that cause an issue?

**Comment by JulianPrieber** [comment]
Could you send me a link to your page? Either here or you can email it to me at: [julian.prieber@llc.ovh](mailto:julian.prieber@llc.ovh)

**Comment by stadler0** [comment]
https://links.stadlerhosting.com/@stadler

**Comment by JulianPrieber** [comment]
How many users are registered on your site?

**Comment by stadler0** [comment]
Two. Me the admin and a friend of mine. The problem shows up for every user I create.

**Comment by JulianPrieber** [comment]
Alright, I think I got an idea why this happens.
Could you try uploading this image as your profile picture?

![try](https://user-images.githubusercontent.com/60265788/224442299-34ee5717-721e-4bd0-815f-3108171abc96.png)

**Comment by stadler0** [comment]
Changed the profile picture to the one you sent but the issue is still there

**Comment by JulianPrieber** [comment]
Weird, the image you were previously using reported to be a WebP not a PNG.

I was able to reproduce this on my phone, tho. I'll look further into it.

**Comment by JulianPrieber** [comment]
Just to be sure, are you using any caching system, like Cloudflare or on your web server?

**Comment by stadler0** [comment]
I am using nginx proxy manager to make the webserver public und running everything over cloudflare because my domain is hosted there

**Comment by JulianPrieber** [comment]
I think I found the issue, I'll issue a new beta in a minute

**Comment by stadler0** [comment]
Wow that was really fast haha I will switch to the beta then. Thank you very much for your help :)

**Comment by JulianPrieber** [comment]
Beta is ready, but not tested yet

**Comment by stadler0** [comment]
The beta fixed the issue. Thank you very much!
