### ISSUE TITLE
Bookwyrm button doesn't appear

### ISSUE THREAD

**Issue by escuco** [JulianPrieber/littlelink-custom#360]
Hello!

Many thanks for adding the Bookwyrm button in the latest release 3.5.1.

I've upgraded to this version, but the button doesn't appear in the predefined sites list.

I have to say that the upgrade via the web updater resulted in a 500 internal server error. After reloading the site, the version number is on 3.5.1.

**Comment by JulianPrieber** [comment]
Please turn on debugging and update again. The updater needs to be able to run system commands to add new buttons.

**Comment by escuco** [comment]
Is there a way to re-trigger the update via webupdater again?
Or should I overwrite the source files manually?

**Comment by JulianPrieber** [comment]
If you enable beta mode, you can always update. Otherwise, just enter a lower number in the version.json in the root directory.

**Comment by escuco** [comment]
Dear Julian,

that did the trick! Thanks for your support.

Jan
