### ISSUE TITLE
Disable registration does not remove "Register"-Link

### ISSUE THREAD

**Issue by DunklerPhoenix** [JulianPrieber/littlelink-custom#371]
Platform: `Debian Buster`
Server type: `Docker`
PHP version: `8.1`

Heho again :P
The "Disable Registration" function does not hide the "Register"-Button on the Login page.
It would be great if the link gets hidden and the /register page shows "Public registration is disabled" or redirects to /

**Comment by JulianPrieber** [comment]
I might be going crazy, but if you're referring to this setting in the config:

![chrome_lIwlD1LYPW](https://user-images.githubusercontent.com/60265788/226720606-cc6edd43-fb97-49c1-857f-f03bd957b59c.png)

this is what it generally does:

<br>

When disabled, hide the Register button
![firefox_QgzYALZKlJ](https://user-images.githubusercontent.com/60265788/226720740-fa1640fa-bfb3-4dea-8467-85fa95529348.png)

When enabled show it
![firefox_e9hGMy06J1](https://user-images.githubusercontent.com/60265788/226720840-ec966af3-9c0d-479d-80af-4e19f85f2c24.png)

When disabled, the register page gets disabled
![firefox_NjgHmSjXdS](https://user-images.githubusercontent.com/60265788/226721196-81461ae5-c12d-4ad5-bc58-bf9f67f277c1.png)

**Comment by DunklerPhoenix** [comment]
> When disabled, the register page gets disabled
Yeah it looks a bit broken. Thats what I meant with the text "Public registration is disabled" on that side

> When disabled, hide the Register button
But not at the /login page ^^ (sry for driving you crazy)
![HxIp58dqPl](https://user-images.githubusercontent.com/1261305/226722068-00668373-4f0a-4c0a-b065-982a4845a2df.png)

**Comment by JulianPrieber** [comment]
Ohhhhhh

**Comment by JulianPrieber** [comment]
right

**Comment by JulianPrieber** [comment]
Do we actually want a message, or should I just 404 the route?

**Comment by DunklerPhoenix** [comment]
I think a message would be better. You can still add the 404 to the header, but if the /register page is somewhere linked, then the message would be an better option i think

**Comment by JulianPrieber** [comment]
How about:

> Registration is disabled by the administrator

**Comment by DunklerPhoenix** [comment]
Sounds great

**Comment by JulianPrieber** [comment]
Fixed in the latest beta
