### ISSUE TITLE
HTTP 500 on homepage when setting it to default to a specific user

### ISSUE THREAD

**Issue by accessiblepixel** [JulianPrieber/littlelink-custom#374]
Hello folks!

I've run into an interesting problem. When I set a user to be the default home page, the website actually returns the HTTP 500 status code (although does actually render the page correctly) when viewing the homepage.

If I navigate to the @ user, then it loads correctly with HTTP 200. It's not a massive problem, although it does make the main site appear to be in an error state to anything that would monitor it externally.

I'm not sure what to do to debug it, I've enabled debugging mode and checked my apache logs and tried updating to the latest version without much luck. I'm using PHP 8.0 at the minute (although could easily swap to 8.1 or 8.2 if those are required, or bump it back to 7.4 - it's hosted on a cloudlinux system).

Would someone be gracious enough to point me in the right direction? I don't really know where to start looking since there's nothing in apache logs or my error_log (since display php errors is turned off but it will log them!)

Kind regards,
Jessica

**Comment by accessiblepixel** [comment]
Yeah, I can, the site I'm having the issue on is https://jcx.contact - that page gives a 500 but renders the page just fine, but if I open my specific page it comes back with a 200 https://jcx.contact/@jcx

I know there was a few things that were being blocked by modsecurity, but I've added exceptions to those rules as they appeared in the log (to exclude them from the issue) - I just can't seem to find out where this 500 is coming from, it's a little frustrating :P 

Thank you!

Kind regards,
Jessica

**Comment by JulianPrieber** [comment]
I again tried to reproduce this issue using your background image and the theme. I made sure to run it on PHP 8.0.
Still with a 200 OK.
Not sure if the app actually causes this.

What happens if you don't have the user set as the home page? Setting the home page to default and accessing the new home page. Does that also return the 500 or is it different here?

<br>

I might need some help here @lastsamurai26

**Comment by accessiblepixel** [comment]
Alright, I've set it to use the default page, and it still gives the 500.

**Comment by JulianPrieber** [comment]
Interesting 🤔 

Could you open your index.php and replace the content with `<?php echo "Hello World!";` and see if that also returns an error 500?

**Comment by accessiblepixel** [comment]
That reports a 200... So... I'm not sure. I also have a wordpress (on a different domain) hosted in the same account (with a different webroot)

**Comment by accessiblepixel** [comment]
Aha! I figured it out!

So in an attempt to debug things, I decided to disable modsecurity, and there was no http 500 response, so that confirmed to me that's where the problem was, but there was nothing showing up in the logs... until I turned on debug logs and got

```
Message: Output filter: Response body too large (over limit of 524288, total not specified).
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client <redacted>] ModSecurity: Output filter: Response
 body too large (over limit of 524288, total not specified). [hostname "jcx.contact"] [uri "/index.php"] [unique_id "Z
BEIqCGusRlELxVCIoPeswABSQ4"]
Apache-Handler: application/x-httpd-ea-php80___lsphp
```
So the fix was to add an override to mod_security2.c in the virtualhost section

```
<IfModule mod_security2.c>
SecResponseBodyLimit 546870912
</IfModule>
```

Which in my case since my HTTPd files are built by cPanel I could add them to ``/etc/apache2/conf.d/userdata/ssl/2_4/<user>/<domain>/reqlimitincrease.conf`` for ssl sites and ``/etc/apache2/conf.d/userdata/std/2_4/<usr>/<domain>/reqlimitincrease.conf`` for http, then trigger a rebuild of http files with ``/usr/local/cpanel/scripts/rebuildhttpdconf`` and then restarting apache ``/usr/local/cpanel/scripts/restartsrv_httpd``, but if you don't use cPanel but do use modsecurity, just put it somewhere in  your <VirtualHost> include :)

All fixed :D
