### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by toddlyons** [JulianPrieber/littlelink-custom#389]
I logged in today and saw "An update is available". I ran the updater from within the app. It backed up, applied it, and claimed to have updated successfully. When I was returned to the admin screen it still reported "An update is available". Just to check, I logged in from a private window, but again: "An update is available".

So, I ran the updater again and it bricked. White screen.

I restored from backup and had the same result, but only ran the updater once, fearing it would brick again.

Is the issue with  version detection? I use other web apps (Matomo, FreshRSS, etc.) which update just fine in the same way.

**Comment by JulianPrieber** [comment]
This strongly indicates that the updater cant write to your files correctly. Please make sure that the web user and group owns and can write to your directory.

**Comment by toddlyons** [comment]
I looked at the permissions and didn't see anything amiss. So, I downloaded the update file, uploaded it to the server, unzipped it there, copied the database over, and deleted the previous installation. I hoped that would fix it, but it led to new errors (which I'll file separately).

**Comment by toddlyons** [comment]
I'm not sure why, but the database from the November 2022 version of this app is not working with the current (as of today) release. I am rolling back to the previous app version.
