### ISSUE TITLE
Feature Request: verification toggle for Mastodon

### ISSUE THREAD

**Issue by dreamcasting** [JulianPrieber/littlelink-custom#394]
Hello,

Thank you so much for your work on this amazing project!  I was curious if it would be possible to have a toggle for Mastodon links to have `rel = “me”` in the metadata. For example `<a href=“#” rel=“me”>` This allows for us to verify accounts on Mastdon under their decentralized model.

More info: https://themarkup.org/levelup/2022/12/22/how-we-verified-ourselves-on-mastodon-and-how-you-can-too

Thank you for your time and consideration!

**Comment by JulianPrieber** [comment]
So you want an option to remove this?

**Comment by JulianPrieber** [comment]
@MagicLike

**Comment by MagicLike** [comment]
> Hello,
> 
> Thank you so much for your work on this amazing project! I was curious if it would be possible to have a toggle for Mastodon links to have `rel = “me”` in the metadata. For example `<a href=“#” rel=“me”>` This allows for us to verify accounts on Mastdon under their decentralized model.
> 
> More info: https://themarkup.org/levelup/2022/12/22/how-we-verified-ourselves-on-mastodon-and-how-you-can-too
> 
> Thank you for your time and consideration!

This is already possible and completely implemented - see my Mastodon profile and my LLC instance as an example:

https://mstdn.social/@MagicLike

https://links.magiclike.net

**Comment by dreamcasting** [comment]
I don’t see an option with the verification meta on my install and I believe it’s on the latest version. I’m just looking to use the functionality and couldn’t find it anywhere. Is it just embedded in the mastodon link type in the app? My profound apologies if so.

**Comment by MagicLike** [comment]
> I don’t see an option with the verification meta on my install and I believe it’s on the latest version. I’m just looking to use the functionality and couldn’t find it anywhere. Is it just embedded in the mastodon link type in the app? My profound apologies if so.

Yes, you just need to add your account via the Mastodon button and link your LLC instance on your Mastodon profile and it should work automatically. So yes - it is integrated in the "link type". ^^

**Comment by colinstu12** [comment]
Does this still work? This no longer seems to be working. Validates just fine for magiclike's acct - no difference with my account yet doesn't pass.

**Comment by MagicLike** [comment]
> Does this still work? This no longer seems to be working. Validates just fine for magiclike's acct - no difference with my account yet doesn't pass.

This was fixed again in the latest updates. Please ensure you have the latest version. If so, try to re-add the URL to your Mastodon profile. (Sometimes Mastodon is a bit rebellious)

**Comment by RZHSSNZDH** [comment]
In the `Page icons` part, mastodon's link does not have this.
