### ISSUE TITLE
Error 500 after install

### ISSUE THREAD

**Issue by tigexplorer** [JulianPrieber/littlelink-custom#403]
Platform: `Ubuntu 22.04 LTS`
Server type: `Apache2 ...`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

HI,
I've put the contents of 
`littlelink-custom` 
in my webserver dir 
`/var/www/sub.mydomain.xyz/public_html`, 

have then changed the owner to 
`chown -R www-data:www-data /var/www/sub.mydomain.xyz/public_html` 
and gave write perm `chmod -R g+rw /var/www/sub.mydomain.xyz/public_html`

I get the **Server Errror 500** but no error in the apache error log.

What's my mistake here?

In the first place, I've forgotten to set the owner to www-data and write perms and got this:
*Permission denied in /var/www/sub.mydomain.xyz/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php*
But now, no error is logged.

**Comment by tilllt** [comment]
Yeah, same issue, Error 500 after installing the docker with default settings, no way to debug when raising log level. 
I think the current Docker setup is broken, too bad.

**Comment by JulianPrieber** [comment]
Please turn on debugging in your .env config file.

![Code_bbWVVcL0vv](https://user-images.githubusercontent.com/60265788/233616262-04f22013-b7de-4afd-aba6-a2c26b6e3781.png)

You might be able to find an error code inside:
`/storage/logs/laravel.log`

**Comment by tigexplorer** [comment]
Ahh,  with sshfs the hidden files wasn't copied...

But now, I get this by the first call: 

```
Illuminate \ Database \ QueryException
PHP 8.1.2-1ubuntu2.11
9.52.5
could not find driver ```
PRAGMA foreign_keys = ON;
```

**Comment by JulianPrieber** [comment]
Are you using MySQL?

**Comment by tigexplorer** [comment]
On the system, yes, but for now, I don't have set any options on LittleLink, according due the docs...

**Comment by JulianPrieber** [comment]
Could you share the stack trace of the error?

**Comment by tigexplorer** [comment]
I hope, this is what you want:

`[resources / views / installer / installer.blade.php : 10](phpstorm://open?file=%2Fvar%2Fwww%2Flnk.onlinekirche.net%2Fpublic_html%2Fresources%2Fviews%2Finstaller%2Finstaller.blade.php&line=10)`

`curl "https:/sub.mydomain.xyz/" \
   -X GET \
   -H 'host: sub.mydomain.xyz' \
   -H 'user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0' \
   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
   -H 'accept-language: de,en-US;q=0.7,en;q=0.3' \
   -H 'accept-encoding: gzip, deflate, br' \
   -H 'dnt: 1' \
   -H 'connection: keep-alive' \
   -H 'cookie: XSRF-TOKEN=eyJpdiI6IjIxa2pXNW9vWHZUT1YzeVZpNllLVGc9PSIsInZhbHVlIjoiRGhMOHZTL2w0ZHlwU1YzQ3VkYzYvZnBSR3pxRUlHeE00aVBxMU1yN1FCTmlWT29CdHJXcjd2c2VWM005bHZ5T3lXRE1vbzBrejZqWVBPQ2hCRzliZFNGSFlOTFdYY29OQS9LWWw2c0I3V3hUdnpPVjNKUlNxTEEzb04yVDRWUCsiLCJtYWMiOiIxNWE2OTc3Y2I1YWU4NTU4NGY4Y2U2ODFmOWJkYjgwMDhlMzEwMjI0NWQ1ZTMzMTE4NjkzZGZiM2Q2OTBiZGNlIiwidGFnIjoiIn0%3D; littlelink_custom_session=eyJpdiI6ImpDWWZ2eWJZTTBjakFOeGt3dUlnWnc9PSIsInZhbHVlIjoiRnBXaGUxcUpRYjdkYmFOelJiVUp1cUdscmhuODA4NFBVVVYrZVBybWdDUnp0amg4dVN4SW5lTkxwQmVTamxaZXJuR3hqWTV3MzJFeG9zUW1jRWhlcURUY1ZPOWxqbWRCalBtMXZOWnpLVDhXQ1RINjM1T3AvNGRSM0xZMXRneDUiLCJtYWMiOiJhZDA4Mzg0MGVlNWIyMjQyOWE4ZTgxYjJhMGIxNThhOTNmZmZiMTRiNDU4ZWZmYWYxYTMzNjZkYWFhMGZiYTA3IiwidGFnIjoiIn0%3D' \
   -H 'upgrade-insecure-requests: 1' \
   -H 'sec-fetch-dest: document' \
   -H 'sec-fetch-mode: navigate' \
   -H 'sec-fetch-site: none' \
   -H 'sec-fetch-user: ?1';`

**Comment by JulianPrieber** [comment]
When you get the error screen, there should be a share button somewhere. Please click that and share the error.

Then you get a link like this that you can post here: https://flareapp.io/share/W7zRk3k7#F55

**Comment by tigexplorer** [comment]
https://flareapp.io/share/oPRN1noP#F64

**Comment by JulianPrieber** [comment]
I'm not sure what's causing this. This could be caused by a missing PHP dependency, but the installer should flag that before running.

I think your best bet is to white everything clean and start new with a fresh installation. Make sure to set the correct file permissions before running the installation process.

**Comment by tigexplorer** [comment]
On a other VM, I've installed like this  

```
curl -O -L https://github.com/JulianPrieber/littlelink-custom/releases/latest/download/littlelink-custom.zip
unzip littlelink-custom.zip
mv littlelink-custom /var/www/mydomain.xy/public_html/
sudo chown -R www-data:www-data /var/www/mydomain.xy/public_html/littlelink-custom/
sudo chmod -R g+rw /var/www/mydomain.xy/public_html/littlelink-custom/
```
and get the same error on first run `https://mydomain.xy/littlelink-custom/`

**Comment by JulianPrieber** [comment]
yeah that wont work

**Comment by JulianPrieber** [comment]
If you pull the app from source, you'll have to compile it first. For that you need composer.

**Comment by JulianPrieber** [comment]
`curl -O -L https://github.com/JulianPrieber/littlelink-custom/releases/latest/download/littlelink-custom.zip`

Does this actually pull the latest release?

**Comment by tigexplorer** [comment]
I've taken the url from the download button on this site:
https://github.com/JulianPrieber/littlelink-custom/releases/tag/v3.6.0

**Comment by JulianPrieber** [comment]
> I've taken the url from the download button on this site:
> https://github.com/JulianPrieber/littlelink-custom/releases/tag/v3.6.0

Right. I had some issues in the past with GitHub's backend to get the actual release file. I just tried running the thing and the release seems to be correct.

**Comment by JulianPrieber** [comment]
This is what the docker image does to get the thing to run without issues.

```
COPY littlelink-custom /htdocs
RUN chown -R apache:apache /htdocs
RUN find /htdocs -type d -print0 | xargs -0 chmod 0755
RUN find /htdocs -type f -print0 | xargs -0 chmod 0644
```

**Comment by tilllt** [comment]
> If you pull the app from source, you'll have to compile it first. For that you need composer.

I used the docker-compose.yml mentioned here 
https://github.com/JulianPrieber/llc-docker,

 using default values, it ends up in Error 500 as well. 
Also, i dont see an .env file in the docker-installation, where is that supposed to be populated from?

**Comment by tigexplorer** [comment]
I got the same error after:

```
sudo find /var/www/zeta-lab.de/public_html/littlelink-custom/ -type d -print0 | sudo xargs -0 chmod 0755
sudo find /var/www/zeta-lab.de/public_html/littlelink-custom/ -type f -print0 | sudo xargs -0 chmod 0644
```

**Comment by JulianPrieber** [comment]
> Also, i dont see an .env file in the docker-installation, where is that supposed to be populated from?

From release/source.

- Are you setting up the thing as a web instance or in docker?
- Are you using SQLite for your installation attempts?

I wouldn't really recommend using the docker compose. If you can in any way use commands, use commands to set it up. Otherwise, you can easily do the same with portainer if you have that setup.

**Comment by tilllt** [comment]
> > Also, i dont see an .env file in the docker-installation, where is that supposed to be populated from?
> 
> From release/source.
> 
> * Are you setting up the thing as a web instance or in docker?
> * Are you using SQLite for your installation attempts?
> 
> I wouldn't really recommend using the docker compose. If you can in any way use commands, use commands to set it up. Otherwise, you can easily do the same with portainer if you have that setup.

I am running all my containers from composer stacks so I'd prefer that way. Are you saying the example docker-compose.yml you provide does not work?

**Comment by JulianPrieber** [comment]
> Are you saying the example docker-compose.yml you provide does not work?

It does work, but apparently not very well. I didn't write it, someone in the community did.
I don't really have much experience writing such files, so my ability to improve or troubleshoot this is fairly limited.

The docker compose file utilizes an alternative method of achieving file persistence which is less storage heavy but has pretty significant flaws.

If I have to set up a docker image, I just run these two commands:
```
docker volume create llc
docker run --detach --name littlelink-custom --publish 8800:80 --publish 8801:443 --restart unless-stopped --mount source=llc,target=/htdocs julianprieber/littlelink-custom
```

**Comment by tilllt** [comment]
> > Are you saying the example docker-compose.yml you provide does not work?
> 
> It does work, but apparently not very well. I didn't write it, someone in the community did. I don't really have much experience writing such files, so my ability to improve or troubleshoot this is fairly limited.
> 
> The docker compose file utilizes an alternative method of achieving file persistence which is less storage heavy but has pretty significant flaws.
> 
> If I have to set up a docker image, I just run these two commands:
> 
> ```
> docker volume create llc
> docker run --detach --name littlelink-custom --publish 8800:80 --publish 8801:443 --restart unless-stopped --mount source=llc,target=/htdocs julianprieber/littlelink-custom
> ```

Ok thanks I will try that

**Comment by tigexplorer** [comment]
It works!
I had to manual install `sqllite`.
Maybe, in the future, it can be checked by the install process?

**Comment by tilllt** [comment]
What do you mean "install SQLite" , install the PHP SQLite extensión?

**Comment by tigexplorer** [comment]
> What do you mean "install SQLite" , install the PHP SQLite extensión?

Yes, this does the trick for me
`sudo apt install php8.1-sqlite3`
and then restart/ reload apache

**Comment by JulianPrieber** [comment]
> Maybe, in the future, it can be checked by the install process?

I'll look into it. Glad it works now.
