### ISSUE TITLE
Wildly unpredictable and random display issues with logo on web app use

### ISSUE THREAD

**Issue by Strats8** [JulianPrieber/littlelink-custom#404]
Platform: Web App/Free-Hosted
OS: LineageOS 19 (Android 12)

LittleLink Custom personal page randomly reverted to previous, unwanted logo and, when trying to fix the issue by uploading new logo, would randomly choose either of previous or actual logo to display even if the file uploaded was the same for all instances.

Link would then display different logos depending on which platform or how it would be accessed (fennec v instagram, etc.)

Clearing all applications cache and rebooting seems to have done the trick but there might be something more there.

F.Y.I. -> not a coder so couldn't possibly debug such issue, can only inform as to what the UX is.

**Comment by Strats8** [comment]
Could this be fixed ?

Either by cache purge (may be load expensive) or shasum checking for the images uploaded (not foolproof) ?

**Comment by JulianPrieber** [comment]
You can add certain headers in your vhost config that make sure no images are cached.
I might add an option to do that in the app. I'd hate to rewrite the entire image system just for that.

**Comment by JulianPrieber** [comment]
I disabled caching for our hosted instance.
Not sure how this will hold up, but it's worth a try.

**Comment by Strats8** [comment]
Wouldn't that overload servers if any pull instance for a *tag* "logo" needs to fetch @PATH ?

**Comment by JulianPrieber** [comment]
Maybe a network bottleneck at some point. For now, I wouldn't consider this a big issue. It might be if you have a **lot** of active users.

**Comment by Strats8** [comment]
Instances are running smoothly for now
-> https://littlelink-custom.llc.ovh/@Amosil

**Comment by Strats8** [comment]
Sorry to have to say, but, *persistent* issue.

Utter randomness when using either redirect (https://littlelink-custom.llc.ovh/@Amosil?fbclid=PAAab_wp7VQU95ICuLK27l5fxaSmmwIY2feBKmHdWdWkOvpe9FzTxiHFo-7XM) or base link (https://littlelink-custom.llc.ovh/@Amosil) through different platforms (fennec, instagram, chrome, etc.)

Side note: Will keep using because performs base function (linktree-like Instagram link repository with proper logo from redirect).

**Comment by Strats8** [comment]
Reverted to a previous, "non-logoed", logo page. A fix would be **greatly** appreciated.

**Comment by JulianPrieber** [comment]
> Reverted to a previous, "non-logoed", logo page. A fix would be greatly appreciated.

Could you please describe your issue in more detail? I'm not sure what you're talking about.

**Comment by Strats8** [comment]
To synthesize - and this is all happening on a free-hosted, web-app instance (https://littlelink-custom.llc.ovh/) using a LineageOS 19, Android 12 custom ROM:

  - I opened up a LittleLink Custom account, made a page.

  - I uploaded a jpg for a logo, submitted it, gave it time, didn't like it.

  - Went back to my account, switched old jpg for new jpg, logo wouldn't change.

  - Through subsequent trials and errors managed to get the new jpg to show as logo.

  - Things seemed steady, the link on my Instagram account redirected to the right page with the right logo.

  - Fiddling around with links (different browsers, Instagram; old cache, new cache, etc.) either from fb redirect or base would display the right page but with a randomness of either of the two uploaded jpgs when only the latest jpg was set and submitted.

  - Got rid of customized logo to get a consistent UX which then always displays the default LLC logo.

Hope this helps

**Comment by Strats8** [comment]
As of 04/26/23, using both base link (https://littlelink-custom.llc.ovh/**) on different browsers and configs as well as using Instagram redirects yields the expected result of having the right logo within the page.

Maybe propagation helped, maybe something else did, but whatever did seems to be working.
*****
