### ISSUE TITLE
No auto multi-line height adjustment?

### ISSUE THREAD

**Issue by thibaultmol** [JulianPrieber/littlelink-custom#405]
I kind of assumed that if I put in text for the button that is longer than one line, it would automatically increase the height of the button. But it doesn't?

![image](https://user-images.githubusercontent.com/1010226/233699106-0a510d87-953e-48fd-8fd4-197ab0c4fd5a.png)

**Comment by JulianPrieber** [comment]
It does not. This is more or less a deliberate choice.
We use the same styling as our parent project for the buttons: https://github.com/sethcottle/littlelink

**Comment by thibaultmol** [comment]
Ah, fair decision then tbh. I'll check upstream if someone has made an issue about the same thing

**Comment by thibaultmol** [comment]
see https://github.com/sethcottle/littlelink/issues/90
