### ISSUE TITLE
It doesn't seem to download the favicon?

### ISSUE THREAD

**Issue by thibaultmol** [JulianPrieber/littlelink-custom#406]
When I add a button that goes to this url
https://uantwerpen.eu.qualtrics.com/jfe/form/SV_ePumOn2Hngciiay
and I click this checkbox
![image](https://user-images.githubusercontent.com/1010226/233699248-04b72e29-472a-4f63-8094-98ae84f7808c.png)

I would assume that it displays the favicon on that url, but it doesn't? it just seems to be a broken image?

**Comment by JulianPrieber** [comment]
https://github.com/JulianPrieber/littlelink-custom/issues/363
