### ISSUE TITLE
Url without the "@" symbol in it

### ISSUE THREAD

**Issue by christiansass** [JulianPrieber/littlelink-custom#413]
Is there a way to get rid of this easily? might be nice to have a toggle to remove it.

eg: https://domain.com/user instead of  https://domain.com/@user

**Comment by christiansass** [comment]
why is it experimental, and at what point do you expect this to be safe?

**Comment by JulianPrieber** [comment]
You can find more detail somewhere on the discussion page.

We don't test this feature in new releases, it might still have some bugs. That's why I don't recommend using it.

Due to the bugs, I wouldn't recommend using this on a public instance as this could break some routes.
