### ISSUE TITLE
Possible to remove 🔗 icon on website header

### ISSUE THREAD

**Issue by iampxyco** [JulianPrieber/littlelink-custom#61]
My question would be if it is possible to remove this icon "🔗" from the title of the pages?
Could you show me the necessary place in which file i can change it, I have not found anything yet.

Thank you!

**Comment by JulianPrieber** [comment]
This should do the trick: [littlelink-custom.zip](https://github.com/JulianPrieber/littlelink-custom/files/8718849/littlelink-custom.zip)
 
If you wish to remove elements from the source code, you can easily find them with the search function provided by GitHub: https://github.com/JulianPrieber/littlelink-custom/search?q=%F0%9F%94%97

If this solved your problem, you can go ahead and close this issue. Should you have any further question, I'm here to help. 

If you like LittleLink Custom so far, feel free to give us a star, as this really helps a lot.

**Comment by iampxyco** [comment]
Thank you, it worked!
Great job, will do it! :)

**Comment by JulianPrieber** [comment]
> My question would be if it is possible to remove this icon "🔗" from the title of the pages? Could you show me the necessary place in which file i can change it, I have not found anything yet.

@iampxyco I haven't forgotten you yet xD. 

This is now possible with the latest version by editing the `advanced-config.php` found in the folder 'config'.

There, simply enter whatever you'd like to have as the title after a user's name in the field: `littlelink_title`.

<details>
    <summary>See:</summary>

<pre>
    // Overwrites default page title after the LittleLink name on LittleLink pages.
    // Example: "admin 🔗 LittleLink Custom"
    //                 ⤌------------------⤍
    //                 ⬑ What you can change with this setting.
    'littlelink_title' => '',
</pre>

</details>
