### ISSUE TITLE
Selecting username at `studio/page` forces reload unless username is changed.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [JulianPrieber/littlelink-custom#758]
### LinkStack version

https://github.com/LinkStackOrg/LinkStack/releases/tag/v4.7.7 (https://linksta.cc/)

### Description

Selecting the username field at https://linksta.cc/studio/page#:~:text=Profile%20Picture-,page%20url forces the user to reload the page, unless they change their username, because it disables the Save button.

### Details about your system

<table><tr>
	<th>OS</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40_Beta-1.10.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td>
</tr></table>

### How to reproduce

[Screencast_20240417_143532.webm](https://github.com/LinkStackOrg/LinkStack/assets/42837531/cfbf0b3b-f947-4afc-b04a-6113dcc1cfe4)

### Possible Solution

If a field's data is replaced by the same data that it already holds, consider it unmodified.

**Comment by MattDevTec** [comment]
I can confirm even accidentally clicking the field causes this problem.

I have experienced it numerous times

**Comment by JulianPrieber** [comment]
Turns out I had accounted for this when implementing this feature. There was **just a typo** in the section that checks for this.

Thank you @RokeJulianLockhart
