### ISSUE TITLE
Headings are not shown correct

### ISSUE THREAD

**Issue by escuco** [JulianPrieber/littlelink-custom#846]
### LinkStack version

4.8.1

### Description

Hello!

First I want to say "thanks" for the newest update v4.8.1, which went through without error messages with the web updater.

But I have a problem with the headings now. As you can see on my site [https://jan.klomp.de](https://jan.klomp.de) , only the placeholder names are shown and not the heading names.

Just for going sure, I deleted the first heading "Websites" and created it new - but with the same result.

Interestingly, in the link editor preview, the headings are shown correct.

### Details about your system

PHP 8.1

### How to reproduce

Make the upgrade and view the site.

**Comment by JulianPrieber** [comment]
Cannot reproduce.

Did you update from a beta or directly from a full release to the latest version?

Try running https://jan.klomp.de/update?finishing step again.

If that fails, you could try to set your version.json to a previous version and try the update again.
It looks like your instance did not perform the preparing step of the update.

**Comment by escuco** [comment]
I've updated from 4.8.0 to 4.8.1.

I tried to run the finishing step again - it runs with success, but the placeholder are still shown.

Then I've set the version number in version.json back to 4.8.0 and started the web updater again - with the same result.

It's strange, that the preview is fine, but not the website.

**Comment by JulianPrieber** [comment]
> It's strange, that the preview is fine, but not the website.

Ah, okay now I understand. I'll work on a fix.
Thank you for the details.

See:
https://jan.klomp.de/@janklomp

**Comment by JulianPrieber** [comment]
@escuco this should be fixed in `v4.8.2`

**Comment by escuco** [comment]
That was really fast!

Thank you so much, works fine now.
